apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vinyl-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hibaarsi/pagWebKub.git
    targetRevision: HEAD
    path: vinyl-app/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: vinyl-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true